### PR TITLE
Wheels 2.0 Version

### PR DESCRIPTION
**Pull request by neokoenig**
Converts to cfscript
Changes bCrypt loading as classpath already mapped
Adds simple box.json (forgebox registration still required)
Adds basic unit tests
Adds Wheels2 javadoc style commenting

### CODE REVIEW

**Comment by andybellenie** [comment]
You know I loathe cfscript, right? :P

Nice one, could you explain the removal of the bCrypt loading though?

**Comment by neokoenig** [comment]
Haha :) Sorry!

Wheels 2.x searches all the `/plugins/` folders on startup and automatically adds them to `this.javasettings` if they have a `.class` or `.jar` file in them, so you don't need to specify the path `/plugins/AuthenticateThis/` anymore.

**Comment by neokoenig** [comment]
Let me know if you want help adding it to forgebox

**Comment by andybellenie** [comment]
Worked, I think... https://www.forgebox.io/view/cfwheels-authenticateThis

**Comment by neokoenig** [comment]
You need to do a tagged release, as forgebox isn't actually pointing at anything;
FYI, I've put a deploy script in there, so from commandbox, assuming you're authenticated with git and forgebox, you just need to do `run-script patch-release` and that will increment the version number, create a tagged release automatically and then push it to forgebox. You'll notice your version number is currently at 0.0.0 as that's just what I set as the default.

Then in the CLI you can do `install cfwheels-authenticateThis` and all's good.

**Comment by andybellenie** [comment]
Thanks, working now

**Pull request merged**
